### ISSUE TITLE
Do you know how to build STAMP transaction?

### ISSUE THREAD

**Issue by joshuaqb** [Jpja/Electrum-Counterparty#3]
https://github.com/hydren-crypto/stampchain/issues/161

I saw your decode page for STAMP protocol, it is great.

Do you know how to compute sign and nonce byte in stamp data?

**Comment by Jpja** [comment]
This is relevant to the legacy Stamp encoding (multisig). The scope of this project is op_return encoding, meaning 99% of Counterparty messages and OLGA Stamps.
